services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

  wordpress:
    build: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    env_file: .env
    restart: always

  mariadb:
    build: ./requirements/mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    env_file: .env
    restart: always

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/medob6/data/wordpress
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/medob6/data/db

networks:
  inception:
    driver: bridge